---
deployment:
  tasks:
    - export DEPLOYPATH=/home/s1052571/public_html/
    - export REPOPATH=/home/s1052571/repositories/sassy-hair/
    - export LOGFILE=${DEPLOYPATH}/deploy_log.txt
    - echo "--- Log Start ---" > ${LOGFILE}
    - ls -la ${REPOPATH} >> ${LOGFILE}
    - cp -a ${REPOPATH}. ${DEPLOYPATH} 2>> ${LOGFILE}
    - echo "--- Copy Attempted ---" >> ${LOGFILE}
    - ls -la ${DEPLOYPATH} >> ${LOGFILE}
    - echo "--- Log End ---" >> ${LOGFILE}
