---
deployment:
  tasks:
    - export DEPLOYPATH=/home/s1052571/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - /bin/find "${DEPLOYPATH}" -type d -exec chmod 755 {} \;
    - /bin/find "${DEPLOYPATH}" -type f -exec chmod 644 {} \;
