// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oilctkpglcqgwdnoihzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbGN0a3BnbGNxZ3dkbm9paHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTgzNjUsImV4cCI6MjA2NzI3NDM2NX0.nf5DpbrO6jL5QKlu5ghJx7tYvpP6PpTV6-DuOwssLVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});